# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json .

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

EXPOSE 8080

# Start the development server with npm run dev
CMD [ "npm", "run", "dev"]

