FROM python:3.11.6-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the current directory into the container at /app
COPY . /app

# Install Flower and its dependencies using pip
RUN pip install flower

# Expose the default Flower port
EXPOSE 5555

# Define the command to run when the container starts
CMD ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
